<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-1AGNC2D" name="testngconcepts.Invocationtimeout" tests="2" failures="0" timestamp="22 Sep 2021 14:05:10 GMT" time="1.026" errors="1">
  <testcase name="login" time="0.008" classname="testngconcepts.Invocationtimeout"/>
  <testcase name="AddCustomer" time="1.018" classname="testngconcepts.Invocationtimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngconcepts.Invocationtimeout.AddCustomer() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngconcepts.Invocationtimeout.AddCustomer() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- AddCustomer -->
</testsuite> <!-- testngconcepts.Invocationtimeout -->
